language: python
cache: pip

matrix:
  include:
    - env: TOXENV="py34-{dj111,dj20}-wt20"
      python: '3.4'
    - env: TOXENV="py35-{dj111,dj20}-wt20"
      python: '3.5'
    - env: TOXENV="py36-{dj111,dj20}-wt20"
      python: '3.6'
    - env: TOXENV="flake8,isort,docs"
      python: '3.6'

install:
  - pip install --upgrade pip wheel tox

script:
  - tox
